/**
 * icons/index.ts — @workspace/design-system
 *
 * !! GENERATED FILE — do not edit by hand.
 * !! Edit icons.json via the lucide-manager picker, then run: lucide-manager generate
 */

export type { IconComponent, IconName } from './icons';
export { ICON_NAMES, icons } from './icons';

// Named icon exports
export const {
  AddIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  BadgeCheckIcon,
  CheckIcon,
  CheckCircleIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronsUpDownIcon,
  ChevronUpIcon,
  ClipboardIcon,
  CloseIcon,
  CoffeeIcon,
  Columns3Icon,
  Columns4Icon,
  CountdownTimerIcon,
  Cross2Icon,
  DeleteIcon,
  DialogIcon,
  DoubleArrowLeftIcon,
  DoubleArrowRightIcon,
  DropdownIcon,
  EditIcon,
  ExclamationTriangleIcon,
  EyeOffIcon,
  EyeOnIcon,
  FastForwardIcon,
  FullscreenIcon,
  GridIcon,
  HomeIcon,
  InfoCircledIcon,
  LanguageIcon,
  ListIcon,
  ListChecksIcon,
  LoaderIcon,
  LockIcon,
  MagnifyingGlassIcon,
  MenuIcon,
  MinimizeIcon,
  MinusIcon,
  MoonIcon,
  PanelBottomCloseIcon,
  PanelBottomOpenIcon,
  PanelLeftCloseIcon,
  PanelLeftOpenIcon,
  PlusIcon,
  RadioIcon,
  RefreshIcon,
  ReloadIcon,
  SettingsIcon,
  ShieldCheckIcon,
  ShuffleIcon,
  SpeakerLoudIcon,
  StarIcon,
  StopIcon,
  SunIcon,
  TempIcon,
  TextAlignLeftIcon,
  TextAlignTopIcon,
  TimerIcon,
  TimerResetIcon,
  TrashIcon,
  UploadIcon,
  UserIcon,
  UserCircleIcon,
  UserLockIcon,
  UserRoundCheckIcon,
  UserShieldIcon,
  VolumeIcon,
  VolumeOffIcon,
  WindowIcon,
  WineIcon,
  XIcon,
  ZapIcon,
} = icons;

// Expose wrapper factory for consumers who need to register app-specific icons
export type { IconProps } from './icons.utils';
export { createIconWrapper } from './icons.utils';
