export type { IconComponent, IconName } from './icons';
export { ICON_NAMES, icons } from './icons';

// Named icon exports — drop-in replacement for `import { XIcon } from 'styles/icons'`
export const {
  // Core UI
  AddIcon,
  BadgeCheckIcon,
  CheckCircleIcon,
  CheckIcon,
  ClipboardIcon,
  CloseIcon,
  CoffeeIcon,
  Columns3Icon,
  Columns4Icon,
  CountdownTimerIcon,
  Cross2Icon,
  DeleteIcon,
  DialogIcon,
  DropdownIcon,
  EditIcon,
  ExclamationTriangleIcon,
  EyeOffIcon,
  EyeOnIcon,
  FastForwardIcon,
  FullscreenIcon,
  GridIcon,
  HomeIcon,
  InfoCircledIcon,
  LanguageIcon,
  ListChecksIcon,
  ListIcon,
  LoaderIcon,
  LockIcon,
  MagnifyingGlassIcon,
  MenuIcon,
  MinimizeIcon,
  MinusIcon,
  MoonIcon,
  PlusIcon,
  RadioIcon,
  RefreshIcon,
  ReloadIcon,
  SettingsIcon,
  ShieldCheckIcon,
  ShuffleIcon,
  SpeakerLoudIcon,
  StarIcon,
  StopIcon,
  SunIcon,
  TempIcon,
  TextAlignLeftIcon,
  TextAlignTopIcon,
  TimerIcon,
  TimerResetIcon,
  TrashIcon,
  UploadIcon,
  UserCircleIcon,
  UserIcon,
  UserLockIcon,
  UserRoundCheckIcon,
  UserShieldIcon,
  VolumeIcon,
  VolumeOffIcon,
  WindowIcon,
  WineIcon,
  XIcon,
  ZapIcon,
  // Navigation — Chevrons
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  DoubleArrowLeftIcon,
  DoubleArrowRightIcon,
  // Panels
  PanelBottomCloseIcon,
  PanelBottomOpenIcon,
  PanelLeftCloseIcon,
  PanelLeftOpenIcon,
} = icons;

// Expose wrapper factory for consumers who need to register app-specific icons
export type { IconProps } from './icons.utils';
export { createIconWrapper } from './icons.utils';
