apps/client/src/api/endpoints/translations.endpoints.ts
apps/client/src/components/LanguageSelector/LanguageSelector.tsx
apps/client/src/components/LanguageSelector/languages/TEST.json
apps/client/src/constants/language.constants.ts
apps/client/src/constants/ui-V2.config.ts
apps/client/src/i18n.config.ts
apps/client/src/pages/AdminPages/AdminTranslationsPage/AdminTranslationsPage.tsx
apps/client/src/pages/AdminPages/AdminTranslationsPage/utils/translation-helpers.ts
apps/client/src/providers/ContentProvider/ContentContext.ts
apps/client/src/providers/ContentProvider/ContentProvider.tsx
apps/client/src/providers/LayoutUiProvider/LayoutUiContext.ts
apps/client/src/providers/LayoutUiProvider/LayoutUiContext.types.ts
apps/client/src/providers/LayoutUiProvider/LayoutUiObserver.tsx
apps/client/src/routes/hooks/useRouteConfig.ts
apps/client/src/types/language.types.ts
apps/client/src/types/models/supported-language.model.ts
apps/client/src/utils/localization.utils.ts
apps/client/src/utils/ui-V2.utils.ts
apps/server/src/db/schemas/container_types.schema.ts
apps/server/src/db/schemas/drink_subtypes.schema.ts
apps/server/src/db/schemas/drink_types.schema.ts
apps/server/src/db/schemas/supported_languages.schema.ts
apps/server/src/db/schemas/volumes.schema.ts
apps/server/src/db/seeds/container_types.seed.ts
apps/server/src/db/seeds/drink_types.seed.ts
apps/server/src/db/seeds/volumes.seed.ts
apps/server/src/routes/container-type/container-type.handlers.ts
apps/server/src/routes/container-type/container-type.routes.ts
apps/server/src/routes/drink-volume/drink-volume.handlers.ts
apps/server/src/routes/drink-volume/drink-volume.routes.ts
apps/server/tsconfig.tsbuildinfo
config/tsconfig.tsbuildinfo
data/migrations/0000_complex_giant_girl.sql
data/migrations/meta/0000_snapshot.json
data/migrations/meta/_journal.json
i18n-complexity-analysis.md
i18n-practical-options.md
language-codes-3b2.csv
package.json
packages/i18n/package.json
packages/i18n/src/constants.ts
packages/i18n/src/constants/app-locales.constants.ts
packages/i18n/src/constants/formatting.constants.ts
packages/i18n/src/constants/index.ts
packages/i18n/src/data/iso-languages-slim.json
