packages:
  - config
  - scripts
  - packages/*
  - apps/*

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - better-sqlite3
  - electron
  - electron-winstaller
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
