// FULL PRETTIER SCHEMA: v3.3.2 / 2024-06-30
// http://json.schemastore.org/prettierrc
// NOTE: annotations generated by ChatGPT

// NOTE: eslint-plugin-prettier will TURN OFF the following ESLint rules:
// 1. "arrow-body-style": "off"
// 2. "prefer-arrow-callback": "off"

const prettierDefaults = {
  arrowParens: 'always',
  bracketSameLine: false,
  bracketSpacing: true,
  cursorOffset: -1,
  embeddedLanguageFormatting: 'auto',
  endOfLine: 'lf',
  hexLiterals: 'uppercase',
  htmlWhitespaceSensitivity: 'css',
  insertPragma: false,
  jsxSingleQuote: false,
  printWidth: 80,
  proseWrap: 'preserve',
  quoteProps: 'as-needed',
  rangeEnd: Infinity,
  rangeStart: 0,
  requirePragma: false,
  semi: true,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: 'es5',
  useTabs: false,
  vueIndentScriptAndStyle: false,
  plugins: [],
  overrides: [],
};

const customOverrides = {
  printWidth: 110,
  singleQuote: true,
  trailingComma: 'all',
  quoteProps: 'consistent',
};

// Import sorting: ESLint handles sorting, Prettier only formats (doesn't sort)
// This allows both to work together - ESLint sorts, Prettier formats without removing blank lines

module.exports = {
  ...prettierDefaults,
  ...customOverrides,
  // DO NOT enable @ianvs/prettier-plugin-sort-imports - it conflicts with ESLint
  // ESLint's simple-import-sort handles all import sorting
  // plugins: ['@ianvs/prettier-plugin-sort-imports'],
  // importOrder: [
  //   // React & External Packages (specific ones first)
  //   '^react',
  //   '^@react',
  //   '^@finografic',
  //   '^@workspace',
  //   // Other external packages
  //   '^@',
  //   '<THIRD_PARTY_MODULES>',
  //   // Internal absolute imports: components, providers, pages
  //   '^(pages|components|lib)(/.*|$)',
  //   // Hooks, routes, providers, queries
  //   '^(hooks|routes|providers|queries)(/.*|$)',
  //   // Utils, types, constants, config
  //   '^(utils)(/.*|$)',
  //   '^(types|constants)(/.*|$)',
  //   '^(config|dev-tools)(/.*|$)',
  //   // Relative imports (parent directories)
  //   '^\\.\\.(?!/?$)',
  //   '^\\.\\./?$',
  //   '^\\./(?=.*/)(?!/?$)',
  //   '^\\.(?!/?$)',
  //   '^\\./?$',
  //   // Styles (CSS imports last)
  //   '^(styles)',
  //   '^.+\\.s?css$',
  //   '^.+\\.styles$',
  // ],
  // importOrderSeparation: true, // Add blank lines between groups
  // importOrderSortSpecifiers: true, // Sort imports within each group
  // importOrderCaseInsensitive: true, // Sort imports case-insensitively
  // importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'], // Parse plugins for import sorting
  // importOrderMergeDuplicateImports: true, // Merge duplicate imports
  // importOrderCombineTypeSpecifier: false, // Combine type specifiers
  // importOrderCombineImportType: true, // Combine import type
  // Prettier will format code but preserve blank lines between import groups
  overrides: [
    {
      files: ['*.ts', '*.tsx', '*.js', '*.jsx'],
      options: {
        // Preserve blank lines - don't collapse multiple blank lines
        // This ensures ESLint's blank lines between import groups are kept
        printWidth: customOverrides.printWidth,
      },
    },
  ],
};
