import { resolve } from 'node:path';

import { defineConfig } from 'tsdown';

const NODE_BUILTINS = [
  'better-sqlite3',
  'fsevents',
  'dotenv',
  'fs',
  'path',
  'os',
  'crypto',
  'node:process',
  'node:os',
  'node:tty',
  'node:path',
  'node:fs',
  'node:url',
  'node:crypto',
  'node:buffer',
  'node:stream',
  'node:http',
  'node:https',
  'node:zlib',
  'node:net',
  'node:events',
  'node:util',
  'node:querystring',
  'node:child_process',
  'node:cluster',
  'node:worker_threads',
  'node:perf_hooks',
  'node:async_hooks',
  'node:timers',
  'node:assert',
  'node:constants',
  'node:domain',
  'node:module',
  'node:punycode',
  'node:readline',
  'node:repl',
  'node:string_decoder',
  'node:tls',
  'node:dgram',
  'node:dns',
  'node:http2',
  'node:inspector',
  'node:v8',
  'node:vm',
];

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm'],
  dts: false,
  clean: true,
  target: 'ES2020',
  sourcemap: false,
  minify: true,
  treeshake: true,
  unbundle: false,
  platform: 'node',
  outDir: 'dist',
  outExtensions: () => ({ js: '.js', dts: '.d.ts' }),
  env: {
    NODE_ENV: 'production',
  },
  define: {
    'process.env.NODE_ENV': '"production"',
  },
  alias: {
    'env.server': resolve(import.meta.dirname, 'env.server.ts'),
  },
  deps: {
    neverBundle: NODE_BUILTINS,
    alwaysBundle: [
      'hono',
      /^@hono\/.*/,
      'drizzle-orm',
      /^@scalar\/.*/,
      '@workspace/core',
      '@workspace/i18n',
      '@workspace/shared',
    ],
  },
});
