export const USER_ROLE = {
  AUTHENTICATOR: 'AUTHENTICATOR',
  ADMIN: 'ADMIN',
  VALIDATED: 'VALIDATED',
  REGISTERED: 'REGISTERED',
  PENDING: 'PENDING',
  GUEST: 'GUEST',
  PUBLIC: 'PUBLIC',
} as const;
