export const ZOD_ERROR_CODES = {
  INVALID_TYPE: 'invalid_type',
  INVALID_LITERAL: 'invalid_literal',
  UNRECOGNIZED_KEYS: 'unrecognized_keys',
  INVALID_UNION: 'invalid_union',
  INVALID_UNION_DISCRIMINATOR: 'invalid_union_discriminator',
  INVALID_ENUM_VALUE: 'invalid_enum_value',
  INVALID_ARGUMENTS: 'invalid_arguments',
  INVALID_RETURN_TYPE: 'invalid_return_type',
  INVALID_DATE: 'invalid_date',
  INVALID_STRING: 'invalid_string',
  TOO_SMALL: 'too_small',
  TOO_BIG: 'too_big',
  CUSTOM: 'custom',
  INVALID_INTERSECTION_TYPES: 'invalid_intersection_types',
  NOT_MULTIPLE_OF: 'not_multiple_of',
  NOT_FINITE: 'not_finite',
} as const;

export const ZOD_ERROR_MESSAGES = {
  [ZOD_ERROR_CODES.INVALID_TYPE]: 'Invalid type',
  [ZOD_ERROR_CODES.INVALID_LITERAL]: 'Invalid literal value',
  [ZOD_ERROR_CODES.UNRECOGNIZED_KEYS]: 'Unrecognized keys in object',
  [ZOD_ERROR_CODES.INVALID_UNION]: 'Invalid union type',
  [ZOD_ERROR_CODES.INVALID_UNION_DISCRIMINATOR]: 'Invalid discriminator value',
  [ZOD_ERROR_CODES.INVALID_ENUM_VALUE]: 'Invalid enum value',
  [ZOD_ERROR_CODES.INVALID_ARGUMENTS]: 'Invalid function arguments',
  [ZOD_ERROR_CODES.INVALID_RETURN_TYPE]: 'Invalid function return type',
  [ZOD_ERROR_CODES.INVALID_DATE]: 'Invalid date',
  [ZOD_ERROR_CODES.INVALID_STRING]: 'Invalid string',
  [ZOD_ERROR_CODES.TOO_SMALL]: 'Value is too small',
  [ZOD_ERROR_CODES.TOO_BIG]: 'Value is too big',
  [ZOD_ERROR_CODES.CUSTOM]: 'Invalid value',
  [ZOD_ERROR_CODES.INVALID_INTERSECTION_TYPES]: 'Invalid intersection types',
  [ZOD_ERROR_CODES.NOT_MULTIPLE_OF]: 'Number must be a multiple of',
  [ZOD_ERROR_CODES.NOT_FINITE]: 'Number must be finite',
} as const;
